server:
  port: 8769

eureka:
  instance:
    hostname: peer2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/

spring:
  application:
    name: peer2-server
  mvc:
    view:
      prefix: /
      suffix: .html
  resources:
    static-locations: classpath:/static,classpath:/temp
