server:
  port: 8762

eureka:
  client:
      service-url:
        defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: eureka-service1

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"