server:
  port: 8755

eureka:
  client:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: xr-feign
feign:
  client:
    default-config:
      connectTimeout: 5000
      readTimeout: 5000
      loggerLevel: basic
  hystrix:
    enabled: true

