server:
  port: 8755

eureka:
  client:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: xr-feign


hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  ConnectTimeout: 10000  #毫秒    连接超时时间
  ReadTimeout: 6000     #毫秒      逻辑处理超时时间
  OkToRetryOnAllOperations: true    # 是否对所有操作都进行重试
  MaxAutoRetries: 1     # 对当前实例的最大重试次数(请求服务超时6s则会再请求一次)
  MaxAutoRetriesNextServer: 2     # 切换实例的最大重试次数(如果还失败就切换下

